### ISSUE TITLE
Incorrect screenshot names

### ISSUE THREAD

**Issue by PhillippOhlandt** [Mikescops/ModdernFolio#3]
Hey,

the last two screenshot names you specified in your composer.json do not exist.

Phillipp

**Comment by Mikescops** [comment]
Thank you :+1:  

That's due to the bolt store update last august ! That was a bit *busy* ^^

**Comment by PhillippOhlandt** [comment]
Have you updated it in the Bolt store? The last two screenshots are broken there.

**Comment by Mikescops** [comment]
My bad again ! Thanks.

**Comment by PhillippOhlandt** [comment]
Now it's perfect, thanks =)
