### ISSUE TITLE
active (dropdown) submenu items don't receive a different color

### ISSUE THREAD

**Issue by 0spinboson** [Mikescops/ModdernFolio#6]
Hi,
thanks for making this theme. :)
I've been trying to fix this myself, but I'm afraid I can't quite figure out which setting to change (or to add), so I hope you can help. 
I would like it if when the active page is listed in a submenu, that submenu entry receives a different color. Could you look into that? Thanks.

**Comment by Mikescops** [comment]
Hello,
Sure I will take a look for you asap.

**Comment by Mikescops** [comment]
Commit 408f3d6 fix this issue !
